import 'package:flutter/material.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert2widget/generated/Generated162111Widget5.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert2widget/generated/GeneratedProductamountWidget3.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert2widget/generated/GeneratedRectangle13Widget1.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert2widget/generated/GeneratedProductgroupWidget3.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert2widget/generated/GeneratedRectangle9Widget1.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert2widget/generated/GeneratedKeyboard_arrow_leftWidget4.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert2widget/generated/GeneratedWidget39.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert2widget/generated/GeneratedWidget48.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert2widget/generated/GeneratedProductgodownWidget2.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert2widget/generated/GeneratedRectangle7Widget3.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert2widget/generated/GeneratedCheck_circle_outlineWidget.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert2widget/generated/GeneratedRectangle10Widget1.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert2widget/generated/GeneratedRectangle8Widget3.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert2widget/generated/GeneratedHomepageWidget5.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert2widget/generated/GeneratedWidget49.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert2widget/generated/GeneratedProductshelfWidget3.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert2widget/generated/GeneratedProductnameWidget3.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert2widget/generated/GeneratedProductpriceWidget2.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert2widget/generated/GeneratedRectangle1Widget5.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert2widget/generated/GeneratedProductskuWidget3.dart';

/* Frame alert2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAlert2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 731.0,
                child: GeneratedHomepageWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 819.0,
                child: Generated162111Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 57.0,
                child: GeneratedRectangle1Widget5(),
              ),
              Positioned(
                left: 20.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 374.0,
                height: 727.0,
                child: GeneratedRectangle7Widget3(),
              ),
              Positioned(
                left: 144.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 35.0,
                child: GeneratedWidget39(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10218978102189781;

                  final double height =
                      constraints.maxHeight * 0.057455540355677154;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.04866180048661801,
                        y: constraints.maxHeight * 0.010943909839468354,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedKeyboard_arrow_leftWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 33.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 77.0,
                child: GeneratedProductnameWidget3(),
              ),
              Positioned(
                left: 35.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 77.0,
                child: GeneratedProductskuWidget3(),
              ),
              Positioned(
                left: 35.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 77.0,
                child: GeneratedProductgroupWidget3(),
              ),
              Positioned(
                left: 35.0,
                top: 527.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 77.0,
                child: GeneratedProductshelfWidget3(),
              ),
              Positioned(
                left: 35.0,
                top: 615.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 77.0,
                child: GeneratedProductgodownWidget2(),
              ),
              Positioned(
                left: 35.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 77.0,
                child: GeneratedProductamountWidget3(),
              ),
              Positioned(
                left: 35.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 77.0,
                child: GeneratedProductpriceWidget2(),
              ),
              Positioned(
                left: 144.0,
                top: 723.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 42.0,
                child: GeneratedRectangle8Widget3(),
              ),
              Positioned(
                left: 183.0,
                top: 731.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 32.0,
                child: GeneratedWidget48(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 731.0,
                child: GeneratedRectangle9Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 731.0,
                child: GeneratedRectangle13Widget1(),
              ),
              Positioned(
                left: 36.0,
                top: 283.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 129.0,
                child: GeneratedRectangle10Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.1362530413625304;

                  final double height =
                      constraints.maxHeight * 0.07660738714090287;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.43795620437956206,
                        y: constraints.maxHeight * 0.40355677154582764,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCheck_circle_outlineWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 142.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 32.0,
                child: GeneratedWidget49(),
              )
            ]),
      ),
    ));
  }
}
