import 'package:flutter/material.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedProductamountWidget2.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedWidget37.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedWidget35.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedProductgodownWidget1.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedProductskuWidget2.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedWidget34.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedRectangle7Widget2.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedRectangle8Widget2.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedWidget36.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedProductnameWidget2.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedHomepageWidget4.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedHelp_outlineWidget.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedProductshelfWidget2.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedProductpriceWidget1.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedProductgroupWidget2.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedRectangle1Widget4.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedWidget25.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedWidget38.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/Generated162111Widget4.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert1widget/generated/GeneratedKeyboard_arrow_leftWidget3.dart';

/* Frame alert1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAlert1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 731.0,
                child: GeneratedHomepageWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 819.0,
                child: Generated162111Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 57.0,
                child: GeneratedRectangle1Widget4(),
              ),
              Positioned(
                left: 20.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 374.0,
                height: 727.0,
                child: GeneratedRectangle7Widget2(),
              ),
              Positioned(
                left: 144.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 35.0,
                child: GeneratedWidget25(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10218978102189781;

                  final double height =
                      constraints.maxHeight * 0.057455540355677154;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.04866180048661801,
                        y: constraints.maxHeight * 0.010943909839468354,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedKeyboard_arrow_leftWidget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 33.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 77.0,
                child: GeneratedProductnameWidget2(),
              ),
              Positioned(
                left: 35.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 77.0,
                child: GeneratedProductskuWidget2(),
              ),
              Positioned(
                left: 35.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 77.0,
                child: GeneratedProductgroupWidget2(),
              ),
              Positioned(
                left: 35.0,
                top: 527.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 77.0,
                child: GeneratedProductshelfWidget2(),
              ),
              Positioned(
                left: 35.0,
                top: 615.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 77.0,
                child: GeneratedProductgodownWidget1(),
              ),
              Positioned(
                left: 35.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 77.0,
                child: GeneratedProductamountWidget2(),
              ),
              Positioned(
                left: 35.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 77.0,
                child: GeneratedProductpriceWidget1(),
              ),
              Positioned(
                left: 144.0,
                top: 723.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 42.0,
                child: GeneratedRectangle8Widget2(),
              ),
              Positioned(
                left: 183.0,
                top: 731.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 32.0,
                child: GeneratedWidget34(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 731.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 731.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 156.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 115.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 208.0,
                height: 32.0,
                child: GeneratedWidget35(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.1362530413625304;

                  final double height =
                      constraints.maxHeight * 0.07660738714090287;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.43309002433090027,
                        y: constraints.maxHeight * 0.38850889192886456,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedHelp_outlineWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 83.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 36.0,
                child: GeneratedRectangle11Widget(),
              ),
              Positioned(
                left: 106.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 32.0,
                child: GeneratedWidget36(),
              ),
              Positioned(
                left: 106.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 32.0,
                child: GeneratedWidget37(),
              ),
              Positioned(
                left: 244.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 36.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 272.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 32.0,
                child: GeneratedWidget38(),
              )
            ]),
      ),
    ));
  }
}
