import 'package:flutter/material.dart';
import 'package:flutterapp/mcstockmanageapp/generatedqrwidget/generated/GeneratedKeyboard_arrow_leftWidget2.dart';
import 'package:flutterapp/mcstockmanageapp/generatedqrwidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/mcstockmanageapp/generatedqrwidget/generated/GeneratedHomepageWidget3.dart';
import 'package:flutterapp/mcstockmanageapp/generatedqrwidget/generated/GeneratedRectangle1Widget3.dart';
import 'package:flutterapp/mcstockmanageapp/generatedqrwidget/generated/GeneratedWidget17.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mcstockmanageapp/generatedqrwidget/generated/Generated162111Widget3.dart';

/* Frame รายละเอียดสินค้า  QR
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQRWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 731.0,
                child: GeneratedHomepageWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 819.0,
                child: Generated162111Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 57.0,
                child: GeneratedRectangle1Widget3(),
              ),
              Positioned(
                left: 144.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 35.0,
                child: GeneratedWidget17(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10218978102189781;

                  final double height =
                      constraints.maxHeight * 0.057455540355677154;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.04866180048661801,
                        y: constraints.maxHeight * 0.010943909839468354,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedKeyboard_arrow_leftWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 21.0,
                top: 109.0,
                right: null,
                bottom: null,
                width: 374.0,
                height: 574.0,
                child: GeneratedGroup4Widget(),
              )
            ]),
      ),
    ));
  }
}
