import 'package:flutter/material.dart';
import 'package:flutterapp/mcstockmanageapp/generatedwidget61/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/mcstockmanageapp/generatedwidget61/generated/GeneratedKeyboard_arrow_leftWidget6.dart';
import 'package:flutterapp/mcstockmanageapp/generatedwidget61/generated/Generated8b7b84fd89eff081dae32fb123b071e01Widget.dart';
import 'package:flutterapp/mcstockmanageapp/generatedwidget61/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mcstockmanageapp/generatedwidget61/generated/GeneratedWidget62.dart';
import 'package:flutterapp/mcstockmanageapp/generatedwidget61/generated/GeneratedScanQRCodeWidget.dart';
import 'package:flutterapp/mcstockmanageapp/generatedwidget61/generated/GeneratedHomepageWidget7.dart';

/* Frame จัดการสินค้า
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget61 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 731.0,
                child: GeneratedHomepageWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 57.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: 157.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 35.0,
                child: GeneratedWidget62(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10218978102189781;

                  final double height =
                      constraints.maxHeight * 0.057455540355677154;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.04866180048661801,
                        y: constraints.maxHeight * 0.01094391244870041,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedKeyboard_arrow_leftWidget6(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 58.0,
                top: 75.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 71.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 144.0,
                top: 95.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 33.0,
                child: GeneratedScanQRCodeWidget(),
              ),
              Positioned(
                left: 84.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 244.0,
                height: 261.0,
                child: Generated8b7b84fd89eff081dae32fb123b071e01Widget(),
              )
            ]),
      ),
    ));
  }
}
