import 'package:flutter/material.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert3widget/generated/GeneratedRectangle9Widget2.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert3widget/generated/GeneratedProductgodownWidget3.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert3widget/generated/GeneratedProductpriceWidget3.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert3widget/generated/GeneratedProductgroupWidget4.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert3widget/generated/GeneratedKeyboard_arrow_leftWidget5.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert3widget/generated/GeneratedProductshelfWidget4.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert3widget/generated/Generated162111Widget6.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert3widget/generated/GeneratedRectangle10Widget2.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert3widget/generated/GeneratedRectangle7Widget4.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert3widget/generated/GeneratedProductskuWidget4.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert3widget/generated/GeneratedRectangle8Widget4.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert3widget/generated/GeneratedRectangle1Widget6.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert3widget/generated/GeneratedProductnameWidget4.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert3widget/generated/GeneratedWarning_amberWidget.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert3widget/generated/GeneratedRectangle13Widget2.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert3widget/generated/GeneratedHomepageWidget6.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert3widget/generated/GeneratedWidget59.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert3widget/generated/GeneratedWidget50.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert3widget/generated/GeneratedProductamountWidget4.dart';
import 'package:flutterapp/mcstockmanageapp/generatedalert3widget/generated/GeneratedWidget60.dart';

/* Frame alert3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAlert3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 731.0,
                child: GeneratedHomepageWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 819.0,
                child: Generated162111Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 57.0,
                child: GeneratedRectangle1Widget6(),
              ),
              Positioned(
                left: 20.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 374.0,
                height: 727.0,
                child: GeneratedRectangle7Widget4(),
              ),
              Positioned(
                left: 144.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 35.0,
                child: GeneratedWidget50(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10218978102189781;

                  final double height =
                      constraints.maxHeight * 0.057455540355677154;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.04866180048661801,
                        y: constraints.maxHeight * 0.010943909839468354,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedKeyboard_arrow_leftWidget5(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 33.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 77.0,
                child: GeneratedProductnameWidget4(),
              ),
              Positioned(
                left: 35.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 77.0,
                child: GeneratedProductskuWidget4(),
              ),
              Positioned(
                left: 35.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 77.0,
                child: GeneratedProductgroupWidget4(),
              ),
              Positioned(
                left: 35.0,
                top: 527.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 77.0,
                child: GeneratedProductshelfWidget4(),
              ),
              Positioned(
                left: 35.0,
                top: 615.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 77.0,
                child: GeneratedProductgodownWidget3(),
              ),
              Positioned(
                left: 35.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 77.0,
                child: GeneratedProductamountWidget4(),
              ),
              Positioned(
                left: 35.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 77.0,
                child: GeneratedProductpriceWidget3(),
              ),
              Positioned(
                left: 144.0,
                top: 723.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 42.0,
                child: GeneratedRectangle8Widget4(),
              ),
              Positioned(
                left: 183.0,
                top: 731.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 32.0,
                child: GeneratedWidget59(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 731.0,
                child: GeneratedRectangle9Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 731.0,
                child: GeneratedRectangle13Widget2(),
              ),
              Positioned(
                left: 36.0,
                top: 283.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 129.0,
                child: GeneratedRectangle10Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.1362530413625304;

                  final double height =
                      constraints.maxHeight * 0.07660738714090287;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.43795620437956206,
                        y: constraints.maxHeight * 0.39808481532147744,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWarning_amberWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 142.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 32.0,
                child: GeneratedWidget60(),
              )
            ]),
      ),
    ));
  }
}
